### ISSUE TITLE
Antwort zu Frage: SYN-1: Wie kann ich einen String in ein Char-Array wandeln?

### ISSUE THREAD

**Issue by MK-NEUKO** [LernMoment/community-fragen#9]
@suchja Hier meine Antwort zur Frage: *<SYN-1: Wie kann ich einen String in ein Char-Array wandeln?>*

```C#
            // Als Erstes wird um eine Eingabe gebeten.
            Console.WriteLine("Bitte Text eingeben: ");
            // Die Eingabe wird in der Variable "text" vom Typ "string" gespeichert.
            string text = Console.ReadLine();
            // erzeugen eines char-Array
            // "text.Length" gibt die Anzahl der Zeichen in "text" als Zahl zurück
            char[] sUD = new char[text.Length];
            // erzeugen der Index-Variable um das Array zu befüllen
            int index = 0;
            // Schleife zum befüllen des Array
            // Die foreach-Schleife hat den besser lesbaren Syntax 
            //und ist weniger Fehleranfällig(Bereichsbasierte Schleife)
            foreach (char c in text)
            {
                sUD[index] = c;
                index++;
            }
            Console.WriteLine();

            // Ausgabe des Array in einer Zeile
            foreach (char c in sUD)
            {
                Console.Write(c);
            }
            Console.WriteLine();

            // Ausgabe des Array durch Zeichen pro Zeile
            foreach (char c in sUD)
            {
                Console.WriteLine(c);
            }
            Console.ReadLine();
```

**Comment by suchja** [comment]
@MK-NEUKO gefällt mir sehr gut! Finde ich ebenfalls eine gute und saubere Lösung.

Magst du von den anderen Fragen auch mal was beantworten? Wie wäre es beispielsweise mit [WPF-1](https://github.com/LernMoment/community-fragen#wpf-1-wie-öffne-ich-ein-unterfenster)?

**Comment by MK-NEUKO** [comment]
@suchja vielen Dank, sowas hört man gerne. Am liebsten würde ich eine Frage nach der anderen Abarbeitung. Leider ist die Zeit zu knapp, die mir dafür zur Verfügung steht. Aber so kleine Happen sind wirklich gut. Ich will aber est tic tac to machen. Ich habe schon die zweite mail bekommen und noch nicht mal angefangen.

**Comment by MK-NEUKO** [comment]
@suchja was ich ganz vergessen habe. Die Aufgabe habe ich damit bearbeitet: https://github.com/radimitrov/CSharpShellApp   Damit bin ich zeitlich gesehen, flexibeler als am PC oder Laptop. Es gibt natürlich Einschränkungen, aber um etwas auszuprobieren, oder eine spontane Idee zu testen, ist es ausreichend.

**Comment by suchja** [comment]
Cool 😎! Das kannte ich noch nicht. In die Richtung gibt es einiges:

https://github.com/dotnet/try

http://www.ahuwanya.net/blog/post/introducing-csharp-pad

Dotnet fiddle

Und bestimmt viele mehr.
